apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: titu-nginx
  template:
    metadata:
      labels:
        app: titu-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
              readOnly: false
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config

